<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 2.11.9.5 setup script by Michal Čihař <michal@cihar.com>
 * Version: $Id: setup.php 12304 2009-03-24 12:56:58Z nijel $
 * Date: Mon, 27 Jul 2009 10:59:01 GMT
 */

/* Servers configuration */
$i = 0;

/* Server mysql.safensound.co.uk (http) [1] */
$i++;
$cfg['Servers'][$i]['host'] = 'mysql.safensound.co.uk';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['auth_type'] = 'http';

/* End of servers configuration */

?>
